FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json first for better cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start dev server
CMD ["npm", "run", "dev"]
