server:
  port: 8080 # Gateway thường chạy ở cổng đẹp nhất 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Định tuyến cho Identity Service
            - id: identity-service
              uri: http://identity-service:8081
              predicates:
                - Path=/identity/**
              filters:
                - AuthenticationFilter
                - StripPrefix=1
            # 2. Tuyến đường MỚI cho Profile Service
            - id: profile-service
              uri: http://profile-service:8082
              predicates:
                - Path=/profile/**
              filters:
                - AuthenticationFilter # Bắt buộc phải có Vé (Token) mới được vào!
                - StripPrefix=1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false